export const STATUSCODEMESSAGES: any = {
  100: "Continue: The request is still in progress. Please wait.",
  101: "Switching Protocols: Switching to a new protocol as requested.",
  102: "Processing: The server is processing your request. Please wait.",
  103: "Early Hints: Preparing to serve the final response.",

  200: "Success: The request was successful.",
  201: "Created: The resource was successfully created.",
  202: "Accepted: Your request has been accepted and is being processed.",
  203: "Non-Authoritative Information: The response contains partial or modified data.",
  204: "No Content: The request was successful, but there is no content to return.",
  205: "Reset Content: The request was successful. Please refresh your view.",
  206: "Partial Content: The server returned only part of the content.",
  207: "Multi-Status: The server processed multiple requests.",
  208: "Already Reported: Duplicate actions were already reported.",
  226: "IM Used: The response was transformed using the Delta encoding.",

  300: "Multiple Choices: Multiple options available. Please choose one.",
  301: "Moved Permanently: The resource has moved to a new URL.",
  302: "Found: The resource is temporarily available at a different URL.",
  303: "See Other: Please see the provided URL for the resource.",
  304: "Not Modified: The resource has not been changed.",
  305: "Use Proxy: Please use a proxy to access this resource.",
  307: "Temporary Redirect: The resource is temporarily at another location.",
  308: "Permanent Redirect: The resource has permanently moved.",

  400: "Bad Request: The server could not understand your request. Please check and try again.",
  401: "Unauthorized: You need to log in to access this resource.",
  402: "Payment Required: Payment is required to access this resource.",
  403: "Forbidden: You do not have permission to access this resource.",
  404: "Not Found: The resource you’re looking for could not be found.",
  405: "Method Not Allowed: This request method is not supported for this resource.",
  406: "Not Acceptable: The resource is not available in the requested format.",
  407: "Proxy Authentication Required: Authentication is required to access through a proxy.",
  408: "Request Timeout: The request took too long. Please try again.",
  409: "Conflict: There was a conflict with the current state of the resource.",
  410: "Gone: The requested resource is no longer available.",
  411: "Length Required: The request did not specify the content length.",
  412: "Precondition Failed: The server conditions were not met.",
  413: "Content Too Large: The request payload is too large to process.",
  414: "URI Too Long: The requested URL is too long.",
  415: "Unsupported Media Type: The request format is not supported.",
  416: "Range Not Satisfiable: The requested range cannot be fulfilled.",
  417: "Expectation Failed: The server cannot meet the expectations set by the request.",
  418: "I’m a teapot: The server refuses to brew coffee in a teapot.",
  421: "Misdirected Request: The request was directed to the wrong server.",
  422: "Unprocessable Content: The server could not process your request.",
  423: "Locked: The resource is locked and cannot be modified.",
  424: "Failed Dependency: A previous request failed, so this action cannot be performed.",
  425: "Too Early: The server is not ready to process this request.",
  426: "Upgrade Required: Please upgrade your client to continue.",
  428: "Precondition Required: Precondition headers are required for this request.",
  429: "Too Many Requests: You have sent too many requests. Please wait and try again later.",
  431: "Request Header Fields Too Large: The request headers are too large to process.",
  451: "Unavailable For Legal Reasons: The resource is unavailable due to legal reasons.",

  500: "Internal Server Error: Something went wrong on our end. Please try again later.",
  501: "Not Implemented: This feature is not supported yet.",
  502: "Bad Gateway: There was an issue with the server. Please try again later.",
  503: "Service Unavailable: The service is temporarily unavailable. Please try again later.",
  504: "Gateway Timeout: The server did not respond in time. Please try again later.",
  505: "HTTP Version Not Supported: The HTTP version is not supported by the server.",
  506: "Variant Also Negotiates: There is a configuration issue on the server.",
  507: "Insufficient Storage: The server is out of storage space.",
  508: "Loop Detected: The server detected an infinite loop.",
  510: "Not Extended: Additional extensions are required for this request.",
  511: "Network Authentication Required: Authentication is required to access this network."
};
